apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-deployment
spec:
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
      # should be same as above 'matchlabels'
        app: catalogue
    spec:
      containers:
      - name: catalogue
        image: absternator/catalogue:v2
        resources:
          limits:
            memory: "128Mi"
            # .5 cpu
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: MongoDbSettings__Host
            value: mongo
          - name: MongoDbSettings__Password
            valueFrom:
              secretKeyRef:
                name: catalogue-secrets
                key: mongodb-password
        # health checks
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 80
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 80
          
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  type: LoadBalancer
  selector:
  # point to pod
    app: catalogue
  ports:
  - port: 80
  # port in container we assigned
    targetPort: 80
